#
# cmake/reflect/_Sources.cmake is generated by `mulle-sde reflect`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( SOURCES
src/mulle-unicode-is-nonpercentescape.c
src/mulle-unicode-is-validurlfragment.c
src/mulle-unicode-is-validurlhost.c
src/mulle-unicode-is-validurlpassword.c
src/mulle-unicode-is-validurlpath.c
src/mulle-unicode-is-validurlquery.c
src/mulle-unicode-is-validurlscheme.c
src/mulle-unicode-is-validurluser.c
)
